pref("nrlorderit.general.print", true);
pref("nrlorderit.general.closeonprint", false);
pref("nrlorderit.general.signaturedate", true);
pref("nrlorderit.general.doubleclicktowebsite", false);
pref("nrlorderit.default.originator", "");
pref("nrlorderit.default.deliverto", "");
pref("nrlorderit.default.priority", "Standard");
pref("nrlorderit.default.unitofissue", "Ea.");
pref("nrlorderit.default.signaturetitle", "");